### ISSUE TITLE
Add Javadoc comments

### ISSUE THREAD

**Issue by gkowligi** [UCSB-CS56-Projects/cs56-games-connectfour#13]
Add in javadoc comments

request 150 points

**Comment by alexisjimenez** [comment]
alexisjimenez: Finished.

**Comment by jrcryan** [comment]
documentation not complete. Every class should have proper javadoc documentation

http://www.tutorialspoint.com/java/java_documentation.htm

**Comment by alexisjimenez** [comment]
alexisjimenez: Revised and Finished

**Comment by SElegans** [comment]
F16 CLOSED: issue resolved
