### ISSUE TITLE
Add another difficulty level in singleplayer

### ISSUE THREAD

**Issue by SharSoft** [UCSB-CS56-Projects/cs56-games-connectfour#17]
Currently:
- Easy mode is random moves by AI.
- Advanced is at novice level
    It knows how to win and block users from winning, but not well enough to be challenging

Add another difficulty level more challenging, called "Insane".
OR
Rename "Advanced" to "Normal", and add an advanced difficulty.

Request ~ 250

**Comment by jrcryan** [comment]
approved

**Comment by SharSoft** [comment]
Completed. Added 12 more block cases to next difficulty level also improving AI winning capability.
