### ISSUE TITLE
Add undo feature in game play

### ISSUE THREAD

**Issue by omeedrabani** [UCSB-CS56-Projects/cs56-games-connectfour#23]
omeedrabani: 
Proposal: add an undo button that removes the most recent move from the board and keeps the correct turn. Removes 1 move for multiplayer and 2 moves for singleplayer (removes the user's move and the computer's move)

~Request 150 points

**Comment by omeedrabani** [comment]
omeedrabani: Completed issue. Is in the Lab06 Pull request.

**Comment by jrcryan** [comment]
~150 points
