### ISSUE TITLE
Add coin toss

### ISSUE THREAD

**Issue by SharSoft** [UCSB-CS56-Projects/cs56-games-connectfour#29]
Simply and a coin toss function in the beginning of the multiplier game to decide who goes first.

Estimate ~ 100 pts

**Comment by jrcryan** [comment]
approved
~100 points

**Comment by bryannaphan** [comment]
**Update:** A randomized "coin toss" to pick which player goes first (for single vs. AI, and multi player) has been made. However, the GUI does not directly indicate that any randomization or coin toss was made. Update the game to somehow indicate that a random selection was made through a coin toss. 
~100 points

**Comment by SElegans** [comment]
F16 OK (100 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
