### ISSUE TITLE
Change Winning Circles Color Size

### ISSUE THREAD

**Issue by omeedrabani** [UCSB-CS56-Projects/cs56-games-connectfour#32]
Change winning circles from full green circles, to show the player's color with smaller inner green circles. Currently, when someone wins the winning circles are covered all in green and cover all of the winner's color. This can be confusing as it may not initially be clear who won. Instead make it so that the winning circles only have a small green inner circle with the full circle of the winner's color behind those green circles (as opposed to making the entire circle green).
~100 points

**Comment by jrcryan** [comment]
approved
~50 points

**Comment by Christiannewkirk** [comment]
Fixed in Pull Request #49.
