### ISSUE TITLE
FIX: After pressing the main menu button from the game board, the buttons are moved.

### ISSUE THREAD

**Issue by sarahmzhong** [UCSB-CS56-Projects/cs56-games-connectfour#42]
This is a previous bug that was listed in the README, but it wasn't posted here.

Known Bugs: After pressing the main menu button from the game board, the buttons are moved down some space.

Request: 200 points

(I just figured this out, and to be honest, it took a really long time...)

**Comment by omeedrabani** [comment]
Approved: 300 pts
