### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by Christiannewkirk** [ucsb-cs56-projects/cs56-games-connectfour#44]
Enhancing the game to look more professional and well coded.
This includes things like using better fonts, organizing buttons/panels better,
and overall creating a better user experience.
 ~300 points

**Comment by omeedrabani** [comment]
W16 OK

**Comment by SElegans** [comment]
F16 OK (300 pts)

**Comment by scottpchow23** [comment]
300 xp

I strongly suggest sketching things out before attempting them in code.

W18 OK
