### ISSUE TITLE
Game Board Color Option

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-games-connectfour#46]
Add in an option to choose the color of the game board, with the option to have a gradient game board, and colors different from the game pieces. This would require another menu to be added to the UI.
~300

**Comment by Christiannewkirk** [comment]
M16 Approved

**Comment by SElegans** [comment]
F16 OK (150 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
