### ISSUE TITLE
Fix winning circles being changed to wrong colors

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-games-connectfour#47]
When a game is won, the winning circles are sometimes set to white, or the loser's color, or a little bit of both. It seems to happen more often when won via a diagonal, but has also happened on vertical and horizontal wins.
~200

**Comment by Christiannewkirk** [comment]
Very similar to issue #32, 200 pts approved if both issues are worked on.

**Comment by Christiannewkirk** [comment]
M16 OK. Fixed in Pull Request #49
