### ISSUE TITLE
Multiplayer namePanel bug

### ISSUE THREAD

**Issue by Christiannewkirk** [UCSB-CS56-Projects/cs56-games-connectfour#50]
When entering Multiplayer mode, the namePanel which states whose turn it is does not accurately update. See the top of the image below.
![image](https://cloud.githubusercontent.com/assets/16568510/16933692/a2e7f4c4-4d04-11e6-81d7-eb1a6075e47b.png)

~150 pts M16

**Comment by SElegans** [comment]
F16 OK (150 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
