### ISSUE TITLE
Bug with turn panel when restarting game

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-games-connectfour#53]
When restarting the game, the turn panel disappears. Our attempt at a fix was left in the code commented out to give you a place to start. Looking at previous versions may also help you, but remember the current version has been refactored extensively.
~200pts

**Comment by Christiannewkirk** [comment]
M16 OK

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
