### ISSUE TITLE
Add in ability to click the "Undo" button after a win

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-games-connectfour#54]
Currently, once a win is detected, you cannot undo the last move. This capability would be very helpful for making boards for testing, so you may even want to bundle this functionality into the "Testing Mode" feature in the settings menu.
~250pts

**Comment by Christiannewkirk** [comment]
M16 OK

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
