### ISSUE TITLE
Improve the Normal AI to detect 2-in-a-rows

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-games-connectfour#57]
Currently, the Normal AI only makes random moves until it detects a 3-in-a-row of either its own color or the opponents, and makes a move accordingly. Improving this to detect 2-in-a-rows would make the Normal AI a bit smarter than the Easy. We would suggest doing this issue before [Issue #56 ](https://github.com/UCSB-CS56-Projects/cs56-games-connectfour/issues/56) to get a better handle on how the AI works.
~150pts

**Comment by Christiannewkirk** [comment]
M16 OK

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
