### ISSUE TITLE
Add in ability to customize player names

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-games-connectfour#58]
Previous versions had the ability to allow players to choose their own names by entering it in a JTextField at the player color section menu. Looking at previous versions may help you get a start at adding this in, and our attempt at adding this in was left commented out in AbstractMenu.java. One approach would be to make an "Enter Name" button which pulls the text from the JTextField.
~150pts

**Comment by Christiannewkirk** [comment]
M16 OK

**Comment by SElegans** [comment]
F16 OK (150 pts)

**Comment by SElegans** [comment]
F16 RESOLVED
