### ISSUE TITLE
Randomly generate AI names

### ISSUE THREAD

**Issue by brianslee** [ucsb-cs56-projects/cs56-games-connectfour#68]
If the input field for the AI's name is left blank, the computer should randomly select a name for the AI. As a bonus, make the pool of names for the AI different. For example, the Easy AI can be named "Wheatley" while the Hard AI can be named "GLaDOS". Assuming that this does not violate copyright or fair use.

Estimate:
300-350pts w/o bonus.
400 w/ bonus

**Comment by SElegans** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
I dont see this being worth as much points as that simply because you are using a random number to select a name from a list of some sort.  If you have a reason it should be worth more, please comment below

**Comment by brianslee** [comment]
There's a bug that crops up when a pre-generated name is placed in the player 2 spot. Not sure why. It crops up randomly. The bug hasn't shown up in the current build, but it may be something that future students run into. But, I'll leave the final decision to you.
