### ISSUE TITLE
Plan to refactor the code base

### ISSUE THREAD

**Issue by samhwkim** [ucsb-cs56-projects/cs56-games-connectfour#78]
There should be a detailed plan to refactor the entire code base since currently the code base does not follow a logical design pattern. I believe this repo can utilize the MVC pattern. This plan will dissect the code and attempt to break up the code base into directories, Model, View, and Controller.

**Comment by scottpchow23** [comment]
200-400 point depending on the quality of the plan. Will go over this in section with you
