### ISSUE TITLE
Allow user to pick a specific song

### ISSUE THREAD

**Issue by efreila** [ucsb-cs56-projects/cs56-games-connectfour#85]
Currently, users can click "Change Music", which randomly selects a song and starts playing it. Users should be allowed to pick a specific song by clicking on a button.

**Comment by efreila** [comment]
Estimate: 150 pts

**Comment by scottpchow23** [comment]
F17 OK (100 pts)

Could be more depending on how thoughtful the implementation is.

**Comment by scottpchow23** [comment]
100 xp

W18 OK
